# Generated by Django 5.2.7 on 2025-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastPasswordResetAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mustChangePassword',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tempPasswordLastSetAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
