# Generated by Django 5.2.8 on 2025-11-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_user_lastpasswordresetat_user_mustchangepassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupHead',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('srno', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Group Head',
                'verbose_name_plural': 'Account Group Heads',
            },
        ),
        migrations.CreateModel(
            name='AccountGroupMaster',
            fields=[
                ('grpcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('initial', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='operations.accountgrouphead')),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
            },
        ),
        migrations.CreateModel(
            name='AccountFinance',
            fields=[
                ('accode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('custcode', models.CharField(blank=True, help_text='Legacy customer code (for migration).', max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('init', models.CharField(blank=True, help_text='Initials.', max_length=10, null=True)),
                ('bankinit', models.CharField(blank=True, help_text='Bank initials.', max_length=10, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('openbal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closbal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closdc', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1)),
                ('currbal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currdc', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1)),
                ('currbal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currdc_usd', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('currbal_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currdc_rmb', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('closbal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closdc_usd', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('closbal_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closdc_rmb', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('open_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('open_rmb', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dc_usd', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('dc_rmb', models.CharField(blank=True, choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=1, null=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('curr', models.ForeignKey(default='INR', on_delete=django.db.models.deletion.PROTECT, to='operations.currency')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer, if this account is for a customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_finance', to='operations.customer')),
                ('grpcode', models.ForeignKey(help_text='Account group (e.g., Bank, Debtors, Funds with Agent).', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='operations.accountgroupmaster')),
            ],
            options={
                'verbose_name': 'Account Finance',
                'verbose_name_plural': 'Account Finance',
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_accounts', to='operations.accountgroupmaster'),
        ),
        migrations.CreateModel(
            name='AccountMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person2', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='operations.accountfinance')),
            ],
            options={
                'verbose_name': 'Account Metadata',
                'verbose_name_plural': 'Account Metadata',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('submit', 'Submit')], max_length=20)),
                ('entity_type', models.CharField(help_text="Model name, e.g. 'Customer', 'AccountFinance'.", max_length=50)),
                ('entity_id', models.BigIntegerField(help_text='Primary key of the affected row.')),
                ('changes', models.JSONField(blank=True, help_text='JSON diff of old vs new values.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Extra info like IP, request id, etc.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accountfinance',
            index=models.Index(fields=['grpcode'], name='operations__grpcode_86e805_idx'),
        ),
        migrations.AddIndex(
            model_name='accountfinance',
            index=models.Index(fields=['currbal', 'currbal_usd', 'currbal_rmb'], name='operations__currbal_507af1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmetadata',
            index=models.Index(fields=['gst_no'], name='operations__gst_no_8d856e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmetadata',
            index=models.Index(fields=['email'], name='operations__email_ab3bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmetadata',
            index=models.Index(fields=['city', 'account'], name='operations__city_704ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='operations__entity__25afeb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='operations__timesta_0e8cfc_idx'),
        ),
    ]
