# Generated by Django 5.2.8 on 2025-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_accountgrouphead_accountgroupmaster_accountfinance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(blank=True, help_text='Stable internal code (e.g. AR_INR, AP_USD).', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_control',
            field=models.BooleanField(default=False, help_text='Marks control accounts like AR/AP, Funds with Agent, main bank accounts.'),
        ),
    ]
